name: Print Runner Name

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  print-runner-name:
    runs-on: [self-hosted, linux]  # Specify your self-hosted runner

    steps:
      - name: Print Runner Name
        run: |
          echo "Hello i m running in gcp"
          uname -a
        
